### ISSUE TITLE
Connect multiple clients to server

### ISSUE THREAD

**Issue by manuelpt4940** [martinohanlon/BlueDot#113]
Good day.

I wonder if I can connect multiple bluetooth devices to BlueDot Server. 

I want to connect my cellphone (I got it) to the Bluedot server in Pi, but I would like to connect simultaniously others bluetooth devices at the same server. Can you help me?

**Comment by martinohanlon** [comment]
To connect multiple devices simultaneously you will need multiple Bluetooth adapters. i.e. the bluetooth on a Pi 3 plus a USB Bluetooth dongle.

There is a code example here https://github.com/martinohanlon/BlueDot/blob/master/examples/multiple_dots.py


This issue has been raised before https://github.com/martinohanlon/BlueDot/issues/63 in summary it's not possible to do it due to constraints with Bluez (linux Bluetooth driver) and Android with only 1 adapter.
